app_token: "cQovpGcdUT1CSzgYk0KPYdAI0"
user_agent: "OpenDataNetwork.com"
timeout_ms: 5000

cache_options:
  expires: 43200

odn_api:
  base: "https://api.opendatanetwork.com"
  entity_lookup_endpoint: "/entity/v1"
  data_availability_endpoint: "/data/v1/availability"
  data_constraint_endpoint: "/data/v1/constraint/{0}"
  data_values_endpoint: "/data/v1/values"

  related_child_endpoint: "/entity/v1/child"
  related_parent_endpoint: "/entity/v1/parent"
  related_peer_endpoint: "/entity/v1/peer"
  related_sibling_endpoint: "/entity/v1/sibling"

  search_dataset_endpoint: "/search/v1/dataset"
  search_question_endpoint: "/search/v1/question"

  map_new_url: "/data/v1/map/new"

autocomplete:
  complete_max_options: 100
  separator: ":"
  shown_options: 5
  url:
    type: "/suggest/v1/${type}"
  wait_ms: 150

related_entity_count: 5
question_count: 10
n_relatives: 5

mobile_width: 800
scroll_threshold: 1000

regions:
  names:
    "region.nation": "Nation"
    "region.region": "Region"
    "region.division": "Division"
    "region.state": "State"
    "region.county": "County"
    "region.msa": "Metro Area"
    "region.place": "Place"
    "region.zip_code": "ZIP Code"
    "region.township": "Township"

  plural_names:
    "region.nation": "Nations"
    "region.region": "Regions"
    "region.division": "Divisions"
    "region.state": "States"
    "region.county": "Counties"
    "region.msa": "Metro Areas"
    "region.place": "Places"
    "region.zip_code": "ZIP Codes"
    "region.township": "Townships"

catalog:
  api: "http://api.us.socrata.com/api/catalog/v1"
  dataset_summary_url: "https://{0}/api/views/{1}.json"
  dataset_migrations_url: "https://{0}/api/migrations/{1}.json"
  athena_url: "https://socrata-athena.herokuapp.com/schema/v1/applied/{0}"

  default_metadata:
    description: ""
    icon: "fa-database"

datasets:
  roster: "https://odn.data.socrata.com/resource/czuf-rtrf.json"
  regions: "https://odn.data.socrata.com/resource/czuf-rtrf.json"

charts:
  options:
    chartArea:
      left: 80
      width: "100%"
    colors:
      - "#2980b9"
      - "#ee3b3b"
      - "#3bdbee"
      - "#ff9900"
      - "#109618"
      - "#0099c6"
      - "#dd4477"
      - "#66aa00"
      - "#b82e2e"
      - "#316395"
    cssClassNames:
      headerCell: "header-cell"
      headerRow: "header-row"
      tableCell: "table-cell"
    curveType: "function"
    height: 300
    legend:
      position : "top"
    lineWidth: 2
    pointShape: "square"
    pointSize: 8
    focusTarget: "category"

maps:
  update_wait: 200
  css_id: 'leaflet-map'
  mapbox:
    token: 'pk.eyJ1IjoibGFuZWFhc2VuIiwiYSI6ImYxZjExYmYzOTMxYzgyZTc2NDY0NDBmNDNmZmEwYWM3In0.uy5ta6EsSEZggkVQHo2ygw'
    label_layer_id: 'socrata-apps.cb421623'
    base_layer_id: 'socrata-apps.af2cc4ed'

  map_options:
    minZoom: 3.0
    maxZoom: 18.0
    zoomControl: false
    attributionControl: false
    scrollWheelZoom: false
    bounceAtZoomLimits: false

  zoom_control: true
  zoom_control_options:
    position: 'topleft'

  initial_zoom_options:
    animate: false
    maxZoom: 10.0
    padding: [140, 140]

  poi_zoom: 11.0
  poi_wait_ms: 100

  base_style:
    fill: true
    fillOpacity: 0.35
    stroke: true
    color: '#2c3e50'
    weight: 1
    opacity: 1

  selected_style:
    weight: 6
    dashArray: '4, 8'
    lineCap: 'round'

  legend_opacity: 0.5
  tooltip_padding: 16

  popup_options:
    closeButton: true
    closeOnClick: false
